# Generated by Django 6.0.2 on 2026-03-16 03:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_delete_jointrainingopportunity'),
        ('training_entities', '0008_remove_trainingopportunity_majors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTrainingOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Matching percentage based on skills and requirements', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Match Score (%)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='training_entities.trainingopportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Training Application',
                'verbose_name_plural': 'Training Applications',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('student', 'opportunity')},
            },
        ),
    ]
