# Generated by Django 6.0.2 on 2026-03-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointrainingopportunity',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('invited', 'Invited'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on_training', 'On Training'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
