# Generated by Django 6.0.2 on 2026-03-08 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/profiles/%Y/%m/', verbose_name='Picture')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='GPA')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='students/cvs/', verbose_name='CV File')),
                ('is_available', models.BooleanField(default=True, help_text='Designates whether this student is currently looking for an internship.', verbose_name='Available for Training')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academy.major', verbose_name='Major')),
                ('skills', models.ManyToManyField(blank=True, related_name='students', to='academy.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
