# Generated by Django 6.0.2 on 2026-03-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/profiles/%Y/%m/', verbose_name='Picture'),
        ),
    ]
