# Generated by Django 6.0.2 on 2026-03-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
