# Generated by Django 6.0.2 on 2026-03-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_jointrainingopportunity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinTrainingOpportunity',
        ),
    ]
