# Generated by Django 6.0.2 on 2026-03-08 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEntityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('entity_name', models.CharField(max_length=255, verbose_name='Entity Name')),
                ('entity_type', models.CharField(choices=[('PRIVATE', 'Private Company/Sector'), ('GOV', 'Government Entity'), ('NGO', 'Non-Profit Organization'), ('RESEARCH', 'Research Center/Academic Center')], default='PRIVATE', max_length=10)),
                ('registration_number', models.CharField(help_text='Commercial Registration Number or Unified Entity Number', max_length=50, verbose_name='CR / Government ID')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='About the Entity')),
                ('is_available', models.BooleanField(default=True, help_text='Designates whether this student is currently looking for an internship.', verbose_name='Available for Training')),
                ('logo', models.ImageField(blank=True, help_text='يفضل مقاس 512x512 بكسل', null=True, upload_to='entities/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, help_text='يفضل صورة عرضية بجودة عالية', null=True, upload_to='entities/covers/', verbose_name='Cover Image')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='students/cvs/', verbose_name='CV File')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_entities', to='core.city', verbose_name='City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Training Entity Profile',
                'verbose_name_plural': 'Training Entity Profiles',
            },
        ),
    ]
