# Generated by Django 6.0.2 on 2026-03-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_entities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingentityprofile',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='trainingentityprofile',
            name='commercial_register',
            field=models.FileField(blank=True, null=True, upload_to='entities/doc/', verbose_name='CV File'),
        ),
    ]
