# Generated by Django 6.0.2 on 2026-03-10 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('training_entities', '0002_remove_trainingentityprofile_cv_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_entities', to='core.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='commercial_register',
            field=models.FileField(blank=True, null=True, upload_to='training_entities/commercial_registers/', verbose_name='Commercial Register'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='A high-quality landscape image is preferred', null=True, upload_to='training_entities/covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='description',
            field=models.TextField(blank=True, max_length=512, verbose_name='About the Entity'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Preferably 512x512 pixels', null=True, upload_to='training_entities/logos/', verbose_name='Logo'),
        ),
    ]
