# Generated by Django 6.0.2 on 2026-03-11 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_university_name'),
        ('core', '0001_initial'),
        ('training_entities', '0003_alter_trainingentityprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Industry Name')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon Class')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='commercial_register',
            field=models.FileField(blank=True, help_text='Upload a copy of your CR or Government ID (PDF)', null=True, upload_to='training_entities/commercial_registers/', verbose_name='Commercial Register'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='description',
            field=models.TextField(blank=True, max_length=512, verbose_name='About the Training Entity'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='entity_name',
            field=models.CharField(max_length=255, verbose_name='Training Entity Name'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='entity_type',
            field=models.CharField(choices=[('PRIVATE', 'Private Company/Sector'), ('GOV', 'Government Entity'), ('NGO', 'Non-Profit Organization'), ('RESEARCH', 'Research Center/Academic Center')], default='PRIVATE', max_length=10, verbose_name='Training Entity Type'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Determines whether the training provider is accredited to operate.', verbose_name='Approved State'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='trainingentityprofile',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Website'),
        ),
        migrations.CreateModel(
            name='TrainingOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Opportunity Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('deadline', models.DateField(verbose_name='Application Deadline')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity')),
                ('other_skills_notes', models.TextField(blank=True, null=True, verbose_name='Other Skills/Tools Notes')),
                ('additional_requirements', models.TextField(blank=True, help_text='Describe any other conditions like GPA, gender, or specific tools.', null=True, verbose_name='Additional Requirements')),
                ('gpa_scale', models.PositiveSmallIntegerField(choices=[(4, '4.0'), (5, '5.0'), (100, '100%')], default=0, help_text='Choose the approved grading system (4, 5, 100%) (optional)', verbose_name='GPA Scale')),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the minimum required score based on the selected scale (optional)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Minimum GPA')),
                ('benefits', models.TextField(blank=True, help_text='Enter the benefits offered to the trainee student.', null=True, verbose_name='Benefits')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_opportunities', to='core.city', verbose_name='City')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='training_entities.industry', verbose_name='Field/Industry')),
                ('majors', models.ManyToManyField(help_text='Choose the university majors required for this opportunity', related_name='opportunities', to='academy.major', verbose_name='Target Majors')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='training_entities.trainingentityprofile', verbose_name='Training Provider')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='opportunities', to='academy.skill', verbose_name='Required Skills')),
            ],
            options={
                'verbose_name': 'Training Opportunity',
                'verbose_name_plural': 'Training Opportunities',
                'ordering': ['-created_at'],
            },
        ),
    ]
