# Generated by Django 6.0.2 on 2026-03-11 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_university_name'),
        ('training_entities', '0004_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingopportunity',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Application Deadline'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='majors',
            field=models.ManyToManyField(blank=True, help_text='Choose the university majors required for this opportunity', related_name='opportunities', to='academy.major', verbose_name='Target Majors'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
