# Generated by Django 6.0.2 on 2026-03-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_entities', '0005_alter_trainingopportunity_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingopportunity',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
    ]
