# Generated by Django 6.0.2 on 2026-03-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_university_name'),
        ('training_entities', '0006_alter_trainingopportunity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingopportunity',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='majors',
            field=models.ManyToManyField(help_text='Choose the university majors required for this opportunity', related_name='opportunities', to='academy.major', verbose_name='Target Majors'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='required_skills',
            field=models.ManyToManyField(related_name='opportunities', to='academy.skill', verbose_name='Required Skills'),
        ),
        migrations.AlterField(
            model_name='trainingopportunity',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
