# Generated by Django 6.0.2 on 2026-03-13 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_university_name'),
        ('training_entities', '0007_alter_trainingopportunity_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingopportunity',
            name='majors',
        ),
        migrations.AddField(
            model_name='trainingopportunity',
            name='major',
            field=models.ForeignKey(default=2, help_text='Choose the university major required for this opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='academy.major', verbose_name='Target Major'),
            preserve_default=False,
        ),
    ]
