# Generated by Django 6.0.2 on 2026-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_profile_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Role Key/Code'),
        ),
    ]
