"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
# from dotenv import dotenv_values

from pathlib import Path

import environ

from django.utils.translation import gettext_lazy as _




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# قراءة ملف .env الفعلي
# environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# # بدلاً من كتابة المفتاح يدوياً، نطلبه من ملف الـ .env
# SECRET_KEY = env('SECRET_KEY')
env = environ.Env(
    # ضبط القيم الافتراضية (في حال لم توجد في ملف .env)
    DEBUG=(bool, False)
)

# 3. قراءة ملف .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 4. استدعاء الأسرار بطريقة احترافية
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

TAILWIND_APP_NAME = 'theme'
# فقط إذا ظهر خطأ يخص npm
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-e!*e6-j$4$*rcx7j+avc(&a5im&0z7#llh_py!a%ahw*7rb1&7'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = []
# style files inputs
TAILWIND_FIELD_CLASSES = (
    "w-full px-4 py-2 mt-1 border border-gray-300 rounded-lg shadow-sm "
    "focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-700 "
    "transition duration-200 outline-none"
)

# Application definition

INSTALLED_APPS = [

    "unfold",  # <-- يجب أن تكون هنا في البداية
    "unfold.contrib.filters",
    "unfold.contrib.forms",

    # 1. تطبيقات Django الأساسية (يجب أن تكون في القمة دائماً)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # ضروري جداً لـ allauth

    # 4. تطبيقاتك البرمجية الخاصة
    'accounts',
    'core',
    'students',

    # 2. تطبيقات Allauth (يجب أن تأتي بعد تطبيقات Django الأساسية)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # 3. تطبيقات التنسيق (Crispy & Tailwind)
    'crispy_forms',
    'crispy_tailwind',
    'tailwind',
    'theme',  # تطبيق الثيم الخاص بك



    # 5. الأدوات الإضافية
    'django_browser_reload',
    "django_htmx",
    'widget_tweaks',

]
UNFOLD = {
    "SITE_TITLE": "لوحة تحكم مشروعي",
    "SITE_SYMBOL": "settings", # أيقونة من Google Fonts
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "500": "168 85 247", # لون بنفسجي جذاب مثلاً
            "600": "147 51 234",
            "900": "88 28 135",
        },
    },
}


# لا تنسى إضافة هذا السطر تحت القائمة مباشرة
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',

    'allauth.account.middleware.AccountMiddleware',

    'django_browser_reload.middleware.BrowserReloadMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
]

# ملف التوجيه الافتراضي  للموقع والذي يبداء الانطلاق منه
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],

            'libraries': {
                'ui_components': 'core.templatetags.ui_components',
            },
            'builtins': [

                'django.templatetags.i18n', # 1. مكتبة الترجمة (عالمية)
                # 'django.templatetags.static',# 2. مكتبة الملفات الثابتة (عالمية لـ CSS/JS)
                'core.templatetags.ui_components', # مكتبة تحميل المكونات القابلة لإعادة الاستخدام
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

TIME_ZONE = 'UTC' # التوقيت العالمي
USE_TZ = True

LANGUAGE_CODE = 'en-us' # اللغة الافتراضية

USE_I18N = True


# قائمة الغات  المتاحة لترجمة
LANGUAGES = [
    ('ar', _('Arabic')),
    ('en', _('English')),
]



LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# مسار حفظ الوسائط
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# إخبار allauth باستخدام الفورم المخصص لحفظ الحقول الإضافية
# ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.forms.CustomSignupForm'

         # منع تكرار الإيميل


LOGIN_URL = 'account_login'  # الرابط الذي يتم توجيه المستخدم إليه إذا حاول دخول صفحة محمية وهو غير مسجل
AUTH_USER_MODEL = 'accounts.CustomUser' # تحديد الModel المعتمد لحساب المستخدم في المشروع
# LOGIN_REDIRECT_URL = 'core:home' # الرابط الذي سيتم الانتقال إليه بعد تسجيل الدخول
LOGIN_REDIRECT_URL = 'accounts:redirect_by_role' #  التوجيه بناءً على "الهوية"
LOGOUT_REDIRECT_URL = 'core:home' # الرابط الذي سيتم الانتقال إليه بعد تسجيل الخروج


ACCOUNT_USERNAME_REQUIRED = False # التأكد من أن allauth لا يبحث عن username

#====================== Email ==========================================


ACCOUNT_AUTHENTICATION_METHOD = "email" # يمكن للمستخدم الدخول عبر الإيميل بدلاً من اليوزر نيم
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
# "mandatory" تجبر المستخدم على التحقق قبل الدخول
# "optional" يرسل بريداً لكن لا يمنعه من الدخول
# "none" لا يرسل بريداً
# ACCOUNT_EMAIL_VERIFICATION = "mandatory" # الزامي رابط التحقق
ACCOUNT_EMAIL_VERIFICATION = "optional"# اختياري رابط التحقق


# . إعدادات خادم البريد (للتجربة أثناء التطوير)
# هذا السطر يطبع الإيميل في التيرمينال بدلاً من إرساله فعلياً
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# settings.py

# . تغيير المحرك من console إلى smtp لإرسال حقيقي
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 2. معلومات سيرفر Gmail
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# 3. بريدك الحقيقي وكلمة مرور التطبيق
EMAIL_HOST_USER = 'azzaldeen771211417@gmail.com'
EMAIL_HOST_PASSWORD = 'cqtj arks oxqk ywzg'  # ليس باسورد الإيميل العادي! (اقرأ التنبيه بالأسفل)

# 4. البريد الذي سيظهر للمرسل إليه (يفضل أن يتطابق مع EMAIL_HOST_USER)
DEFAULT_FROM_EMAIL = 'Django Web | Support <azzaldeen771211417@gmail.com>'

# ====================================================================================

handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

DEFAULT_HOME_URL = 'core:home'
# config/settings.py

SITE_ROLES = [
    # {'code': 'user', 'name': 'user', 'is_identity': True ,'requires_approval': False,'view_in_register': True},
    {'code': 'student', 'name': 'student', 'is_identity': True ,'requires_approval': False,'view_in_register': True,},
    {'code': 'company', 'name': 'company', 'is_identity': True,'requires_approval': True,'view_in_register': True},
]

#ربط هذه الأدوار بلوحات التحكم الخاصة بها

ROLE_DASHBOARDS = {
    # 'user': 'users:dashboard',
    'student': 'students:dashboard',
    'company': 'companies:dashboard',
    'admin': 'admin:index'
}


# إعدادات Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"
