# Generated by Django 6.0.2 on 2026-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='University Name'),
        ),
    ]
